package codewars

type Game struct {
	RandomSeed                             int64
	TickCount                              int
	WorldWidth                             float64
	WorldHeight                            float64
	FogOfWarEnabled                        bool
	VictoryScore                           int
	FacilityCaptureScore                   int
	VehicleEliminationScore                int
	ActionDetectionInterval                int
	BaseActionCount                        int
	AdditionalActionCountPerControlCenter  int
	MaxUnitGroup                           int
	TerrainWeatherMapColumnCount           int
	TerrainWeatherMapRowCount              int
	PlainTerrainVisionFactor               float64
	PlainTerrainStealthFactor              float64
	PlainTerrainSpeedFactor                float64
	SwampTerrainVisionFactor               float64
	SwampTerrainStealthFactor              float64
	SwampTerrainSpeedFactor                float64
	ForestTerrainVisionFactor              float64
	ForestTerrainStealthFactor             float64
	ForestTerrainSpeedFactor               float64
	ClearWeatherVisionFactor               float64
	ClearWeatherStealthFactor              float64
	ClearWeatherSpeedFactor                float64
	CloudWeatherVisionFactor               float64
	CloudWeatherStealthFactor              float64
	CloudWeatherSpeedFactor                float64
	RainWeatherVisionFactor                float64
	RainWeatherStealthFactor               float64
	RainWeatherSpeedFactor                 float64
	VehicleRadius                          float64
	TankDurability                         int
	TankSpeed                              float64
	TankVisionRange                        float64
	TankGroundAttackRange                  float64
	TankAerialAttackRange                  float64
	TankGroundDamage                       int
	TankAerialDamage                       int
	TankGroundDefence                      int
	TankAerialDefence                      int
	TankAttackCooldownTicks                int
	TankProductionCost                     int
	IfvDurability                          int
	IfvSpeed                               float64
	IfvVisionRange                         float64
	IfvGroundAttackRange                   float64
	IfvAerialAttackRange                   float64
	IfvGroundDamage                        int
	IfvAerialDamage                        int
	IfvGroundDefence                       int
	IfvAerialDefence                       int
	IfvAttackCooldownTicks                 int
	IfvProductionCost                      int
	ArrvDurability                         int
	ArrvSpeed                              float64
	ArrvVisionRange                        float64
	ArrvGroundDefence                      int
	ArrvAerialDefence                      int
	ArrvProductionCost                     int
	ArrvRepairRange                        float64
	ArrvRepairSpeed                        float64
	HelicopterDurability                   int
	HelicopterSpeed                        float64
	HelicopterVisionRange                  float64
	HelicopterGroundAttackRange            float64
	HelicopterAerialAttackRange            float64
	HelicopterGroundDamage                 int
	HelicopterAerialDamage                 int
	HelicopterGroundDefence                int
	HelicopterAerialDefence                int
	HelicopterAttackCooldownTicks          int
	HelicopterProductionCost               int
	FighterDurability                      int
	FighterSpeed                           float64
	FighterVisionRange                     float64
	FighterGroundAttackRange               float64
	FighterAerialAttackRange               float64
	FighterGroundDamage                    int
	FighterAerialDamage                    int
	FighterGroundDefence                   int
	FighterAerialDefence                   int
	FighterAttackCooldownTicks             int
	FighterProductionCost                  int
	MaxFacilityCapturePoints               float64
	FacilityCapturePointsPerVehiclePerTick float64
	FacilityWidth                          float64
	FacilityHeight                         float64
}
